### ISSUE TITLE
Unittests for DeviceMap

### ISSUE THREAD

**Issue by ALSchwalm** [ALSchwalm/mythril#19]
We need test the we can't, for example, register multiple devices that service the same io ports. We should also just have more tests to ensure the logic in the device lookup is correct.

**Comment by ALSchwalm** [comment]
Related to #27

**Comment by barkera** [comment]
I'll look into this

**Comment by ALSchwalm** [comment]
Fixed in 040d72ef808bd6c0e0e92a27e0f53d03412c2e82. Thanks Adam!
